# Gradle
org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true
org.gradle.daemon = false

# Project
mod_version = 1.21.1-3.0.0-beta

mod_id = moonlight
mod_name = Moonlight Lib
mod_author = MehVahdJukaar
mod_description = A small library with many cool unique features, from dynamic asset generation to dynamic villager schedules, data driven trades and Map Markers, simple multi loader utilities and more
mod_license = Supplementaries Team License v.1.5
mod_authors = MehVahdJukaar
mod_homepage = https://www.curseforge.com/minecraft/mc-mods/selene
mod_github = https://github.com/MehVahdJukaar/moonlight
mod_credits = MehVahdJukaar

release_type = beta
maven_group = net.mehvahdjukaar


# Publishing
repository = mehvahdjukaar/moonlight
curseforge_project_id = 499980
modrinth_project_id = moonlight

mc_version = 1.21.1


parchment_mappings_version = 2024.11.17
neoforge_version = 21.1.228


fabric_loader_version = 0.17.2
fabric_api_version = 0.116.6+1.21.1

mixin_extras_version = 0.5.4
sable_version_comp = 1.21.1-1.6.0
candlelight_version = 1.0.3



flywheel_minecraft_version = 1.19.2
flywheel_version = 0.6.6-6
cca_version = 5.2.1
modmenu_version = 11.0.0
cloth_version = 11.0.99






