architectury {
    common(rootProject.enabled_platforms.split(','))
}

loom {
    accessWidenerPath = file("src/main/resources/moonlight.accesswidener")

}

sourceSets.create("example"){
    var main = sourceSets.main
    compileClasspath += main.compileClasspath + main.output
    runtimeClasspath += main.runtimeClasspath + main.output
}

repositories {
    // For some reason, this maven only works here, not in the root build.gradle
    maven {
        name = "Valkyrien Skies Internal"
        url = 'https://maven.valkyrienskies.org'
        // I wish I could make this repo exclusiveContent for VS,
        // but for some reason then it tries to get VS from jitpack,
        // and refuses to import (even if you exclude VS from jitpack, it still fails to get VS from... jitpack!)
        // so... blame gradle :(
    }
}

dependencies {
    // We depend on fabric loader here to use the fabric @Environment annotations and get the mixin dependencies
    // Do NOT use other classes from fabric loader
    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    // Remove the next line if you don't want to depend on the API
    //modApi "dev.architectury:architectury:${rootProject.architectury_version}"
    implementation(annotationProcessor("com.github.bawnorton.mixinsquared:mixinsquared-common:${mixin_squared_version}"))
    implementation("com.github.bawnorton.mixinsquared:mixinsquared-forge:${mixin_squared_version}")

    modCompileOnly("curse.maven:yacl-667299:4523734")
    modCompileOnly("curse.maven:modernfix-790626:4599353")
    modCompileOnly ("curse.maven:map-atlases-forge-519759:5018175")
    modImplementation ("curse.maven:configured-457570:5096828")
    modCompileOnly("curse.maven:quark-243121:5344451")

    // VS2
    modApi("org.valkyrienskies:valkyrienskies-120-common:${rootProject.vs2_version}") {
        // Exclude create for speed
        exclude group: "com.simibubi"
        // Exclude moonlight because we ARE moonlight
        exclude group: "maven.modrinth", module: "moonlight"
    }
    implementation("org.valkyrienskies.core:api:${rootProject.vs_core_version}")
    implementation("org.valkyrienskies.core:impl:${rootProject.vs_core_version}")
    implementation("org.valkyrienskies.core:internal:${rootProject.vs_core_version}")


    modCompileOnly("curse.maven:irisshaders-455508:5789255")

    implementation(annotationProcessor("io.github.llamalad7:mixinextras-fabric:0.3.6"))

    annotationProcessor 'net.fabricmc:sponge-mixin:0.12.5+mixin.0.8.5'

}

publishing {
    publications {
        mavenCommon(MavenPublication) {
            artifactId = rootProject.mod_id
            from components.java
        }
    }
}

